AWSTemplateFormatVersion: 2010-09-09
Description: Template that deploys Database and Storage for our dummy application
Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    DatabaseIdentifier:
        AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
        ConstraintDescription: The DB instance identifier is case-insensitive, but is stored as all lowercase (as in "mydbinstance"). Constraints - 1 to 60 alphanumeric characters or hyphens. First character must be a letter. Can't contain two consecutive hyphens. Can't end with a hyphen.
        Description: DB instance identifier
        MinLength: 1
        MaxLength: 60
        Type: String
    DatabaseName:
        AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
        ConstraintDescription: Specify a string of up to 64 alpha-numeric characters that define the name given to a database that Amazon RDS creates when it creates the DB instance, as in “mydb”.
        Description: Initial database name
        MinLength: 1
        MaxLength: 64
        Type: String
    DatabaseUsername:
        AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
        ConstraintDescription: 1 to 16 alphanumeric characters. First character must be a letter.
        Description: Username for MySQLDB
        MinLength: 1
        MaxLength: 16
        NoEcho: true
        Type: String
    DatabasePassword:
        AllowedPattern: '[a-zA-Z0-9]*'
        ConstraintDescription: At least 8 printable ASCII characters. Can't contain any of the following - / (slash), '(single quote), "(double quote) and @ (at sign).
        Description: Password for MySQLDB
        MinLength: 8
        MaxLength: 42
        NoEcho: true
        Type: String
    DatabaseStorage:
        ConstraintDescription: (Minimum - 20 GiB. Maximum - 16,384 GiB) Higher allocated storage may improve IOPS performance.
        Description: The size of the database in GiB
        MinValue: 20
        MaxValue: 16384
        Type: Number
Resources:   
    DatabaseSubnet:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: Subnet group for RDS database
            SubnetIds: 
                - Fn::ImportValue: !Sub ${EnvironmentName}-PRI1-SN
                - Fn::ImportValue: !Sub ${EnvironmentName}-PRI2-SN
            Tags:
                - Key: Name
                  Value: database subnets
    mySQLDatabase:
        Type: AWS::RDS::DBInstance
        Properties:
            Engine: MySQL
            EngineVersion: 8.0.27
            DBInstanceIdentifier: !Ref DatabaseIdentifier
            MasterUsername: !Ref DatabaseUsername
            MasterUserPassword: !Ref DatabasePassword
            DBInstanceClass: db.t2.micro
            AllocatedStorage: !Ref DatabaseStorage
            AvailabilityZone: !Select [ 0, !GetAZs  '' ]
            DBSubnetGroupName: !Ref DatabaseSubnet
            DBName: !Ref DatabaseName