AWSTemplateFormatVersion: 2010-09-09
Description: Deploys a database for our dummy application
Resources:
    MyDB:
      Type: AWS::RDS::DBInstance
      Properties:
        DBSecurityGroups:
        - Ref: MyDbSecurityByEC2SecurityGroup
        - Ref: MyDbSecurityByCIDRIPGroup
        AllocatedStorage: '5'
        DBInstanceClass: db.t2.small
        Engine: MySQL
        MasterUsername: MyName
        MasterUserPassword: MyPassword
      DeletionPolicy: Snapshot